export const ADD_TO_BOOKMARK = "ADD_TO_BOOKMARK";

export const DELETE_FROM_BOOKMARK = "DELETE_FROM_BOOKMARK";

export const SYNC_BOOKMARKS = "SYNC_BOOKMARKS";

export const SYNC_BOOKMARKS_MAP = "SYNC_BOOKMARKS_MAP";
